### ISSUE TITLE
load F.interpolate scales.weights() error

### ISSUE THREAD

**Issue by syshensyshen** [onnx/onnx-tensorrt#398]

**Comment by syshensyshen** [comment]
when i use tensorrt load model,
![image](https://user-images.githubusercontent.com/13030181/74702271-74db3c00-5244-11ea-8c61-81faadcca72b.png)

**Comment by TengFeiHan0** [comment]
have you ever solve this problem?

**Comment by kevinch-nv** [comment]
This is a limitation in TRT where we do not allow dynamic scales for our resize layer. 

In later ONNX versions ([since opset 11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Resize-11)) the resize operator has been updated where you can specify the size of the resized tensor rather than the scales. TRT has better support for resizes where the size is specified over scales.

Can you export your model to at least opset 11, ensure that the resize operator has been exported with the `sizes` input populated over `scales`, and try importing the model into TRT again?

**Comment by kevinch-nv** [comment]
Closing due to no repro, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.
