### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by aif2017** [onnx/onnx-tensorrt#415]
I think your docker build doesn't work with Tensorrt 7?
please repair...

**Comment by rmccorm4** [comment]
Hi,

As mentioned in the README, please refer to the TensorRT build instructions instead of this repo's build instructions. 

Here's an example of how you could build TensorRT OSS components (including onnx-tensorrt files located in TensorRT/parsers/onnx): https://github.com/NVIDIA/TensorRT/issues/433#issuecomment-599299704

**Comment by Ru-Van** [comment]
@rmccorm4, @kevinch-nv 
Hi. I try to build your dockerFile with Tensorrt 7, but faced with next problem:
1. cmake version. 
`apt install cmake` 
This command by default install **3.10.2** version in Ubuntu18.4, but a version higher **than 3.13** is required.
I solved this adding next code in dockerFile:
`RUN wget https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Linux-x86_64.sh&& \
 chmod +x cmake-3.14.4-Linux-x86_64.sh&& \
 ./cmake-3.14.4-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license&& \
 rm cmake-3.14.4-Linux-x86_64.sh`
2. Problem with swig. 
`swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
NvOnnxParser.h:213: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
`
I really don't know how to solve this. 

And i try to build docker, because directly to install i can't. I really don' t understand how to install python - onnx_tensorrt module, it's not clear from your description. 
As far as I understand below is a description of how to install TensorRt, but how to install onnx_tensorrt module?
### Building
For building on master, we recommend following the instructions on the master branch of TensorRT as there are new dependencies that were introduced to support these new features.
To build on older branches refer to their respective READMEs.
__________________________________________________________
Do you support this direction? It makes sense to consider your implementation?

**Comment by kevinch-nv** [comment]
We have updated both our docker installation process and `setup.py` script to better streamline the build process in the latest TRT 7.2 release. 

I will be closing this issue, if you have any problems building on TRT 7.2 feel free to open a new one.
