### ISSUE TITLE
Alternative to loading the onnx model 

### ISSUE THREAD

**Issue by mrunal-byt** [onnx/onnx-tensorrt#582]
```
import onnx
import onnx_tensorrt.backend as backend
import numpy as np

model = onnx.load("/path/to/model.onnx")
engine = backend.prepare(model, device='CUDA:1')
input_data = np.random.random(size=(32, 3, 224, 224)).astype(np.float32)
output_data = engine.run(input_data)[0]
print(output_data)
print(output_data.shape)

#my code
```

I want to run this code frequently and this code takes a long time to run because of loading and preparing the backend. 
Is there an alternative that reduces this time. All I want is save the backend model somewhere and load that model only,  so that it might take lesser time to run.

**Comment by kevinch-nv** [comment]
You are correct, the bulk of the time consists of building the engine, which the backend is doing everytime in that code snippet.

In order to remove the engine building overhead, the workflow is to build the engine once, and save the engine to disk to reload in future inference runs. It looks like the backend doesn't have a clear function to do that, so marking this as an enhancement. 

I'll work on a MR adding this.

**Comment by kevinch-nv** [comment]
Closing since we recommend the usage of (trtexec)[https://github.com/NVIDIA/TensorRT/tree/main/samples/trtexec] to serialize models.
