### ISSUE TITLE
Status of onnx-tensorrt in the future

### ISSUE THREAD

**Issue by varunvelpula** [onnx/onnx-tensorrt#718]
I read multiple comments by the contributors that trtexec which comes with the TensorRT library would succeed onnx-tensorrt, thus making onnx-tensorrt deprecated. Is this true?

I am currently confused on which one to continue using for my project

**Comment by kevinch-nv** [comment]
When you say `onnx-tensorrt`, there are two potential meanings:

1. The `onnx2trt` binary - you are correct that this will eventually be succeeded by `trtexec` since `trtexec` is more up to date.
2. The parser library itself `libnvonnxparser.so`. Both `onnx2trt` and `trtexec` link against this library, so the core code and thus this repository will still be relevant. The recommend workflow is to build the parser library from this repository and update your `LD_LIBRARY_PATH` to link `trtexec` to it.
